services:
  backend:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - ./app:/code/app
    secrets:
      - github_token
secrets:
    github_token:
      file: ./secrets/github_token.txt
